server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json

application:
  title: 'API de Clientes'
  version: 1.0.0

spring:
  application:
    name: customer-api

cassandra:
  cluster: 'Test Cluster'
  addresses: localhost
  port: 9042
  username: root
  password: password
  keyspace: customer

eureka:
  client:
    enabled: false
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka